### PR TITLE
HubCap: Bump snowplow/dbt-snowplow-web

### PR DESCRIPTION
**Pull request by drewbanin**
Auto-bumping from new release at https://github.com/snowplow/dbt-snowplow-web/releases

### CODE REVIEW

**Review by jtcohen6 — COMMENTED** [review]
Hmm... I was expecting to see `require-dbt-version: [">=1.0.0", "<2.0.0"]` here, now that https://github.com/dbt-labs/hubcap/pull/146 has been merged, and since it's [defined in the package](https://github.com/snowplow/dbt-snowplow-web/blob/0.9.1/dbt_project.yml#L5).

@joellabes @dbeatty10 Does either of you know if there's a manual step to redeploy Hubcap changes to Heroku?

**Comment by joellabes** [comment]
@jtcohen6 ugh yes there is a manual step at the moment, in the aftermath of that Heroku incident where all the oauth tokens were reset (or whatever happened).

directions at https://www.notion.so/dbtlabs/Incident-Heroku-Deploys-from-GitHub-Unavailable-for-hub-getdbt-com-167153eaa107450bb1ee5e42a8945b0f#b60dc252ec874dc1ae60e5ae63d9c743

**Comment by dbeatty10** [comment]
Even better, the Hubcap release instructions are here:
[https://github.com/dbt-labs/hubcap/blob/main/RELEASE.md](https://github.com/dbt-labs/hubcap/blob/main/RELEASE.md#heroku-production-release-manual)

**Comment by dbeatty10** [comment]
@jtcohen6 Hubcap has been re-deployed.

https://github.com/dbt-labs/hub.getdbt.com/pull/1779 is merged.

Opened https://github.com/dbt-labs/hub.getdbt.com/issues/1790 to address the small delta of packages there were updated before #1779 was merged.

**Pull request merged**
