### PR TITLE
update favicon

### PR DESCRIPTION
**Pull request by dave-connors-3**
this PR updates the favicon for the hub site!

Steps:
1. clone docs.getdbt.com repo
2. copy [this file](https://github.com/dbt-labs/docs.getdbt.com/blob/current/website/static/img/favicon.ico)
3. overwrite current `favicon.ico` with this one!

cc: @jtcohen6

### CODE REVIEW

**Comment by drewbanin** [comment]
@dave-connors-3 many thanks!! Let's ship it when the build passes :)

**Comment by dave-connors-3** [comment]
@drewbanin I think it unfortunately did not work! the build version still has the old icon - I think it could related to the submodule? not really sure how that works to be honest!

**Comment by drewbanin** [comment]
I think you actually did the right thing @dave-connors-3! The problem is that the favicon points to the prod URL of the icon even in staging, eg:
```
<link href="https://hub.getdbt.com/images/favicon.ico" rel="icon" type="image/ico">
```

So, the icon is present in the staging env, but we're pointing the the prod version of the icon. We can verify that here: https://deploy-preview-594--flamboyant-mcclintock-92ba2d.netlify.app/images/favicon.ico

Think we're good to just merge this PR :)

**Review by drewbanin — APPROVED** [review]

**Comment by drewbanin** [comment]
Looks good in prod - nice work @dave-connors-3 :D

**Pull request merged**
