### PR TITLE
Remove git submodules from installation instructions

### LINKED ISSUE #1788: Allow community members to run the website locally
## Overview
As noted in #1774, there's a private submodule that is a blocker for building locally for any community members outside of the dbt-labs organization.

If we remove this blocker, than any community member can build the [hub.getdbt.com](https://github.com/dbt-labs/hub.getdbt.com) website locally and participate in development.

## Implementation steps
- [X] copy the CSS files from the `fishtown-analytics/www.getdbt.com` submodule to an internal folder.
    - #1782
- [X] remove it from `.gitmodules`
    - #1782
- [x] remove it from any instructions (like [here](https://github.com/dbt-labs/hub.getdbt.com/blob/24f0eb7aff841fdbf6418f68f9f7f4e13135047f/CONTRIBUTING.md#development))
    - #1789
- [X] add a Dockerfile
    - #1794
- [ ] add a docker-compose and instructions
    - #1802

### PR DESCRIPTION
**Pull request by dbeatty10**
Continues #1788 (bulk of the work in #1782).

Assuming the necessary Ruby environment is all set up, the install+run instructions are now as simple as:

> Install dependencies with `bundler` and run with middleman:
> ```bash
> bundle install
> bundle exec middleman serve --port 4567
> ```

### CODE REVIEW

**Comment by b-per** [comment]
Hey @dbeatty10 , I think there is just a little bit more to it.

Looking at https://github.com/dbt-labs/hub.getdbt.com/issues/1757, the default `Gemfile` didn't run for me, and I struggled quite a bit with my local machine + Docker to get something working.
I shared in that issue what `Gemfile` worked on my M1.

From here, as a temporary solution we could:
1. (can be done now, but hacky) modify the contribution instructions and mention that the `Gemfile` that comes from the repo needs to be updated before running `bundle install` locally
2. (more work to do, but clean) modify the `Gemfile` of the repo to both work for the deployment of the Hub and local development

**Review by b-per — CHANGES_REQUESTED** [review]
I have added some comments

**Comment by dbeatty10** [comment]
Thanks for those comments @b-per 

I added a question about Docker [here](https://github.com/dbt-labs/hub.getdbt.com/issues/1757#issuecomment-1225763590) (which you already answered!).

Here's essentially the diff of your Gemfile vs. the current one:
```diff
 source 'https://rubygems.org'
 
-gem 'execjs', '2.8.1'
-gem 'therubyracer', :platforms => :ruby
 gem 'middleman', '~> 4.4'
 gem 'middleman-autoprefixer', '~> 3.0.0'
 gem 'middleman-livereload', '3.4.7'
-gem 'less'
 gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
 gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]
 gem 'redcarpet', '3.5.1'
```

To test those changes, I think this is what we'd do:
1. Make the changes to `Gemfile`
1. Produce a `Gemfile.lock` via [these](https://github.com/dbt-labs/hub.getdbt.com/blob/master/CONTRIBUTING.md#managing-the-gemfile-and-gemfilelock) instructions
    - There's a bootstrapping problem here -- whoever does the locking already needing to have a working local environment
1. Open a pull request with those changes
1. Click the *deploy/netlify* "details" button to see the deployment that represents these changes
    image
1. Perform any relevant testing
    - we do not currently have a defined list of manual or automatic tests of website behavior and functionality

**Comment by dbeatty10** [comment]
Re-requesting review now that https://github.com/dbt-labs/hub.getdbt.com/pull/1794 is merged.

I think these commands should execute just fine assuming the Ruby environment is all set up (via Docker or any other method).

**Review by b-per — APPROVED** [review]

**Comment by b-per** [comment]
The instructions should work now, yes!

It might be worth also adding instructions on how to run the website via Docker but it could be added either in this PR or another one.

**Comment by dbeatty10** [comment]
> The instructions should work now, yes!
> 
Awesome!

> It might be worth also adding instructions on how to run the website via Docker but it could be added either in this PR or another one.

Agreed -- opened #1802 to add `docker compose` + relevant instructions

**Pull request merged**
